
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yomal Randunu
 */
public class Assessment extends javax.swing.JFrame {

    /**
     * Creates new form Assessment
     */
    public Assessment() {
        initComponents();
        Show_Assessmentc_In_JTable();
    }
    
    
     public ArrayList<Assessmentc> getAssessmentcList()
    {
        Connection conn=null;
        ArrayList<Assessmentc> AssessmentcList = new ArrayList<Assessmentc>(); 
        conn=MysqlConnect.ConnectDB();
        String query="SELECT * FROM  assessment"; 
        Statement st;
        ResultSet rs;
        try {
            st=conn.createStatement();
            rs=st.executeQuery(query);
            Assessmentc assessmentc;
            
            while(rs.next())
            {
                assessmentc=new Assessmentc(rs.getString("Assess_no"),
                        rs.getString("Assess_name"),
                        rs.getString("Module_no")
                        );
               AssessmentcList.add( assessmentc);
            }
        } catch (SQLException e) {
        }
        return  AssessmentcList;
    }
    
    public void Show_Assessmentc_In_JTable()
    {
         ArrayList<Assessmentc> List = getAssessmentcList();
         DefaultTableModel model =(DefaultTableModel)jTableAssessment.getModel();
         Object[] row = new Object[4];
          for (int i = 0; i< List.size();i++) {
            
              row[0]= List.get(i). getAsse_id();
              row[1]= List.get(i). getAsse_name();
              row[2]= List.get(i). getmodule_no();
           
              
              model.addRow(row);
            
        }
    }
       //execute the sql querys 
    public void executeQuery(String query,String message){
        Connection conn = MysqlConnect.ConnectDB();
        Statement st;
        
        try{
        st=conn.createStatement();
        if((st.executeUpdate(query))== 1)
        {
            
            //refresh the jtable
            DefaultTableModel model = ( DefaultTableModel)jTableAssessment.getModel();
            model.setRowCount(0);
            Show_Assessmentc_In_JTable();
            
            JOptionPane.showMessageDialog(null,"data"+ message+"Successfully");
        }else
            JOptionPane.showMessageDialog(null,"data not"+ message);
        
        
    }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
    }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAssename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldmod = new javax.swing.JTextField();
        jToggleButtonsave5 = new javax.swing.JToggleButton();
        jTextFieldAsseid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jToggleButtonupdate5 = new javax.swing.JToggleButton();
        jToggleButtondelete5 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAssessment = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Assessment Id");

        jLabel7.setText("Assessment name");

        jLabel8.setText("Module No");

        jToggleButtonsave5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/19-32.png"))); // NOI18N
        jToggleButtonsave5.setText("Insert");
        jToggleButtonsave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsave5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Assessment Details");

        jToggleButtonupdate5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/43-32.png"))); // NOI18N
        jToggleButtonupdate5.setText("Update");
        jToggleButtonupdate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonupdate5ActionPerformed(evt);
            }
        });

        jToggleButtondelete5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/50-32.png"))); // NOI18N
        jToggleButtondelete5.setText("Delete");
        jToggleButtondelete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtondelete5ActionPerformed(evt);
            }
        });

        jTableAssessment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assessment ID", "Assessment Name", "Module No"
            }
        ));
        jTableAssessment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAssessmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAssessment);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("University Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButtonsave5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel9))
                                            .addComponent(jLabel8))
                                        .addGap(87, 87, 87)))
                                .addComponent(jToggleButtondelete5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonupdate5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAsseid, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(jTextFieldmod)
                                    .addComponent(jTextFieldAssename))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAsseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldAssename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldmod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jToggleButtonsave5)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtondelete5)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonupdate5)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAssessmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAssessmentMouseClicked
        int i =jTableAssessment.getSelectedRow();
        TableModel model = jTableAssessment.getModel();
        jTextFieldAsseid.setText(model.getValueAt(i,0).toString());
        jTextFieldAssename.setText(model.getValueAt(i,1).toString());
        jTextFieldmod.setText(model.getValueAt(i,2).toString());
       
    }//GEN-LAST:event_jTableAssessmentMouseClicked

    private void jToggleButtondelete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtondelete5ActionPerformed
        String query = "DELETE FROM  assessment WHERE `Assess_no`='"+jTextFieldAsseid.getText()+"'";
        executeQuery(query, "Deleted");
    }//GEN-LAST:event_jToggleButtondelete5ActionPerformed

    private void jToggleButtonupdate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonupdate5ActionPerformed
        String query = " UPDATE `university`.` assessment` SET `Assess_no`='"+jTextFieldAsseid.getText()+"',`Assess_name`='"+jTextFieldAssename.getText()+"', `Module_no`='"+jTextFieldmod.getText()+"' WHERE `Assess_no`='"+jTextFieldAsseid.getText()+"'";
        // UPDATE `university`.`student` SET `Stu_id`='"+jTextFieldid.getText()+"', `F_name`='"+jTextFieldfirst.getText()+"', `M_name`='"+jTextFieldmiddle.getText()+"', `L_name`='"+jTextFieldlast.getText()+"', `email`='"+jTextFieldemail.getText()+"', `NIC`='"+jTextFieldnic.getText()+"', `Address`='"+jTextFieldaddress.getText()+"',`Batch_id`='"+jTextFieldbatchid.getText()+"' WHERE `Stu_id`='"+jTextFieldid.getText()"';
        executeQuery(query, "Inserted");
    }//GEN-LAST:event_jToggleButtonupdate5ActionPerformed

    private void jToggleButtonsave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsave5ActionPerformed
        /*        String Student_id = jTextFieldid.getText();
        String first_name = jTextFieldfirst.getText();
        String middle_name = jTextFieldmiddle.getText();
        String last_name = jTextFieldlast.getText();
        String address = jTextFieldaddress.getText();
        String email = jTextFieldemail.getText();
        String nic = jTextFieldnic.getText();
        String Batch_id = jTextFieldbatchid.getText();
        Connection conn =null;
        PreparedStatement pst=null;
        try{
            conn=MysqlConnect.ConnectDB();
            pst=conn.prepareStatement("INSERT INTO student VALUES (?,?,?, ?, ?, ?, ?,?)");
            pst.setString(1, Student_id);
            pst.setString(2, first_name);
            pst.setString(3, middle_name);
            pst.setString(4, last_name);
            pst.setString(5, email);
            pst.setString(6, nic);
            pst.setString(7, address);
            pst.setString(8, Batch_id);
            int i = pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Data Save");

            }else
            JOptionPane.showMessageDialog(null, "Data not save");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }

        */

        String query="INSERT INTO `university`.` assessment` (`Assess_no`, `Assess_name`, `Module_no`) VALUES ('"+jTextFieldAsseid.getText()+"',"+jTextFieldAssename.getText()+"','"+jTextFieldmod.getText()+"')";
        executeQuery(query,"inserted");
    }//GEN-LAST:event_jToggleButtonsave5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assessment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAssessment;
    private javax.swing.JTextField jTextFieldAsseid;
    private javax.swing.JTextField jTextFieldAssename;
    private javax.swing.JTextField jTextFieldmod;
    private javax.swing.JToggleButton jToggleButtondelete5;
    private javax.swing.JToggleButton jToggleButtonsave5;
    private javax.swing.JToggleButton jToggleButtonupdate5;
    // End of variables declaration//GEN-END:variables
}
