
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yomal Randunu
 */
public final class Faculty extends javax.swing.JFrame {

    /**
     * Creates new form Faculty
     */
    public Faculty() {
        initComponents();
         Show_Facultyc_In_JTable();
    }
    
    
     public ArrayList<Facultyc> getFacultycList()
    {
        Connection conn=null;
        ArrayList<Facultyc> FacultycList = new ArrayList<Facultyc>(); 
        conn=MysqlConnect.ConnectDB();
        String query="SELECT * FROM  faculty"; 
        Statement st;
        ResultSet rs;
        try {
            st=conn.createStatement();
            rs=st.executeQuery(query);
            Facultyc facultyc;
            
            while(rs.next())
            {
                facultyc=new Facultyc(rs.getString("F_id"),
                        rs.getString("F_name")
                        );
               FacultycList.add(facultyc);
            }
        } catch (SQLException e) {
        }
        return  FacultycList;
    }
     
     
      public void Show_Facultyc_In_JTable()
    {
         ArrayList< Facultyc> List = getFacultycList();
         DefaultTableModel model =(DefaultTableModel)jTablefaculty.getModel();
         Object[] row = new Object[3];
          for (int i = 0; i< List.size();i++) {
            
              row[0]= List.get(i). getF_id();
              row[1]= List.get(i). getF_name();
              
          
              model.addRow(row);
            
        }
    }
      
      
          //execute the sql querys 
    public void executeQuery(String query,String message){
        Connection conn = MysqlConnect.ConnectDB();
        Statement st;
        
        try{
        st=conn.createStatement();
        if((st.executeUpdate(query))== 1)
        {
            
            //refresh the jtable
            DefaultTableModel model = ( DefaultTableModel)jTablefaculty.getModel();
            model.setRowCount(0);
            Show_Facultyc_In_JTable();
            
            JOptionPane.showMessageDialog(null,"data"+ message +"Successfully");
        }else
            JOptionPane.showMessageDialog(null,"data not"+ message);
        
        
    }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
    }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablefaculty = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldfid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jToggleButtonsave1 = new javax.swing.JToggleButton();
        jToggleButtondelete1 = new javax.swing.JToggleButton();
        jToggleButtonupdate1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablefaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty ID", "Faculty Name"
            }
        ));
        jTablefaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablefacultyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablefaculty);

        jLabel1.setText("Faculty ID");

        jLabel2.setText("Faculty Name");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel3.setText("University Management System");

        jToggleButtonsave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/19-32.png"))); // NOI18N
        jToggleButtonsave1.setText("Insert");
        jToggleButtonsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsave1ActionPerformed(evt);
            }
        });

        jToggleButtondelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/50-32.png"))); // NOI18N
        jToggleButtondelete1.setText("Delete");
        jToggleButtondelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtondelete1ActionPerformed(evt);
            }
        });

        jToggleButtonupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/43-32.png"))); // NOI18N
        jToggleButtonupdate1.setText("Update");
        jToggleButtonupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonupdate1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Faculty Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldfid)
                            .addComponent(jTextFieldfname)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtondelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButtonsave1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtondelete1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonupdate1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsave1ActionPerformed
        /*        String Student_id = jTextFieldid.getText();
        String first_name = jTextFieldfirst.getText();
        String middle_name = jTextFieldmiddle.getText();
        String last_name = jTextFieldlast.getText();
        String address = jTextFieldaddress.getText();
        String email = jTextFieldemail.getText();
        String nic = jTextFieldnic.getText();
        String Batch_id = jTextFieldbatchid.getText();
        Connection conn =null;
        PreparedStatement pst=null;
        try{
            conn=MysqlConnect.ConnectDB();
            pst=conn.prepareStatement("INSERT INTO student VALUES (?,?,?, ?, ?, ?, ?,?)");
            pst.setString(1, Student_id);
            pst.setString(2, first_name);
            pst.setString(3, middle_name);
            pst.setString(4, last_name);
            pst.setString(5, email);
            pst.setString(6, nic);
            pst.setString(7, address);
            pst.setString(8, Batch_id);
            int i = pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Data Save");

            }else
            JOptionPane.showMessageDialog(null, "Data not save");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);

        }

        */

        String query="INSERT INTO `university`.`faculty` (`F_id`, `F_name`) VALUES ('"+jTextFieldfid.getText()+"','"+jTextFieldfname.getText()+"')";
        executeQuery(query,"inserted");

    }//GEN-LAST:event_jToggleButtonsave1ActionPerformed

    private void jToggleButtondelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtondelete1ActionPerformed
        String query = "DELETE FROM faculty WHERE `F_id`='"+jTextFieldfid.getText()+"'";

        executeQuery(query, "Deleted");
    }//GEN-LAST:event_jToggleButtondelete1ActionPerformed

    private void jToggleButtonupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonupdate1ActionPerformed
        String query = " UPDATE `university`.`faculty` SET `F_id`='"+jTextFieldfid.getText()+"', `F_name`='"+jTextFieldfname.getText()+"' WHERE `F_id`='"+jTextFieldfid.getText()+"'";
        
        executeQuery(query, "Inserted");

    }//GEN-LAST:event_jToggleButtonupdate1ActionPerformed

    private void jTablefacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablefacultyMouseClicked
        // TODO add your handling code here:
           int i =jTablefaculty.getSelectedRow();
        TableModel model = jTablefaculty.getModel();
        jTextFieldfid.setText(model.getValueAt(i,0).toString());
        jTextFieldfname.setText(model.getValueAt(i,1).toString());
       
                            
    }//GEN-LAST:event_jTablefacultyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablefaculty;
    private javax.swing.JTextField jTextFieldfid;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JToggleButton jToggleButtondelete1;
    private javax.swing.JToggleButton jToggleButtonsave1;
    private javax.swing.JToggleButton jToggleButtonupdate1;
    // End of variables declaration//GEN-END:variables
}
