
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yomal Randunu
 */
public final class Modules extends javax.swing.JFrame {

    /**
     * Creates new form Moduels
     */
    public Modules() {
        initComponents();
        Show_Modulesc_In_JTable();
    }
    
        
    public ArrayList<Modulesc> getModulescList()
    {
        Connection conn=null;
        ArrayList<Modulesc> ModulescList = new ArrayList<Modulesc>(); 
        conn=MysqlConnect.ConnectDB();
        String query="SELECT * FROM  modules"; 
        Statement st;
        ResultSet rs;
        try {
            st=conn.createStatement();
            rs=st.executeQuery(query);
            Modulesc modulesc;
            
            while(rs.next())
            {
                modulesc=new Modulesc(rs.getString("Md_no"),
                        rs.getString("Md_name"),
                        rs.getString("Level_no"),
                        rs.getString("Degree_id")
                        );
                ModulescList.add(modulesc);
            }
        } catch (SQLException e) {
        }
        return ModulescList;
    }
    
    public void Show_Modulesc_In_JTable()
    {
         ArrayList<Modulesc> List = getModulescList();
         DefaultTableModel model =(DefaultTableModel)jTableModuel.getModel();
         Object[] row = new Object[5];
          for (int i = 0; i< List.size();i++) {
            
              row[0]= List.get(i). getMd_no();
              row[1]= List.get(i). getMd_name();
              row[2]= List.get(i). getLevel_no();
              row[3]= List.get(i). getDegree_id();
             
              model.addRow(row);
            
        }
    }
    
    //execute the sql querys 
    public void executeQuery(String query,String message){
        Connection conn = MysqlConnect.ConnectDB();
        Statement st;
        
        try{
        st=conn.createStatement();
        if((st.executeUpdate(query))== 1)
        {
            
            //refresh the jtable
            DefaultTableModel model = ( DefaultTableModel)jTableModuel.getModel();
            model.setRowCount(0);
            Show_Modulesc_In_JTable();
            
            JOptionPane.showMessageDialog(null,"data" + message+ "Successfully");
        }else
            JOptionPane.showMessageDialog(null,"data not" + message);
        
        
    }catch(HeadlessException | SQLException e){
         JOptionPane.showMessageDialog(null,e);
    }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModuel = new javax.swing.JTable();
        jTextFieldMid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldMname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMlevel = new javax.swing.JTextField();
        jToggleButtonsave3 = new javax.swing.JToggleButton();
        jToggleButtondelete3 = new javax.swing.JToggleButton();
        jToggleButtonupdate3 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDegreeid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableModuel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Moduel ID", "Moduel Name", "Level", "Degree ID"
            }
        ));
        jTableModuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableModuelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableModuel);

        jLabel3.setText("Moduel ID");

        jLabel10.setText("Moduel Name");

        jLabel7.setText("Level");

        jToggleButtonsave3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/19-32.png"))); // NOI18N
        jToggleButtonsave3.setText("Insert");
        jToggleButtonsave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsave3ActionPerformed(evt);
            }
        });

        jToggleButtondelete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/50-32.png"))); // NOI18N
        jToggleButtondelete3.setText("Delete");
        jToggleButtondelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtondelete3ActionPerformed(evt);
            }
        });

        jToggleButtonupdate3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/43-32.png"))); // NOI18N
        jToggleButtonupdate3.setText("Update");
        jToggleButtonupdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonupdate3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Modules Details");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("University Management System");

        jLabel8.setText("Degree ID ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMname, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldMid, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDegreeid, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButtonsave3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtondelete3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButtonupdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDegreeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addComponent(jToggleButtonsave3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtondelete3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonupdate3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonsave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsave3ActionPerformed

        String query="INSERT INTO `university`.`modules` (`Md_no`, `Md_name`, `Level_no`, `Degree_id`) VALUES ('"+jTextFieldMid.getText()+"','"+jTextFieldMname.getText()+"','"+jTextFieldMlevel.getText()+"','"+jTextFieldDegreeid.getText()+"')";
        executeQuery(query,"inserted");
    }//GEN-LAST:event_jToggleButtonsave3ActionPerformed

    private void jToggleButtondelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtondelete3ActionPerformed
        String query = "DELETE FROM modules WHERE `Md_no`='"+jTextFieldMid.getText()+"'";

        executeQuery(query, "Deleted");
    }//GEN-LAST:event_jToggleButtondelete3ActionPerformed

    private void jToggleButtonupdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonupdate3ActionPerformed
        String query = " UPDATE `university`.`modules` SET `Md_no`='"+jTextFieldMid.getText()+"', `Md_name`='"+jTextFieldMname.getText()+"', `Level_no`='"+jTextFieldMlevel.getText()+"', `Degree_id`='"+jTextFieldDegreeid.getText()+"' WHERE `Md_no`='"+jTextFieldMid.getText()+"'";

        executeQuery(query, "Inserted");
    }//GEN-LAST:event_jToggleButtonupdate3ActionPerformed

    private void jTableModuelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModuelMouseClicked
        // TODO add your handling code here:
          int i =jTableModuel.getSelectedRow();
        TableModel model = jTableModuel.getModel();
        jTextFieldMid.setText(model.getValueAt(i,0).toString());
        jTextFieldMname.setText(model.getValueAt(i,1).toString());
        jTextFieldMlevel.setText(model.getValueAt(i,2).toString());
        jTextFieldDegreeid.setText(model.getValueAt(i,3).toString());
      
    }//GEN-LAST:event_jTableModuelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Modules().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModuel;
    private javax.swing.JTextField jTextFieldDegreeid;
    private javax.swing.JTextField jTextFieldMid;
    private javax.swing.JTextField jTextFieldMlevel;
    private javax.swing.JTextField jTextFieldMname;
    private javax.swing.JToggleButton jToggleButtondelete3;
    private javax.swing.JToggleButton jToggleButtonsave3;
    private javax.swing.JToggleButton jToggleButtonupdate3;
    // End of variables declaration//GEN-END:variables
}
