
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yomal Randunu
 */
public class ResultPhone extends javax.swing.JFrame {

    /**
     * Creates new form ResultPhone
     */
    public ResultPhone() {
        initComponents();
        Show_ResultPhone_In_JTable();
    }
    
    
     public ArrayList<ResultPhonec> getResultPhonecList()
    {
        Connection conn=null;
        ArrayList<ResultPhonec> ResultPhonecList = new ArrayList<ResultPhonec>(); 
        conn=MysqlConnect.ConnectDB();
        String query="SELECT su.Stu_id,su.F_name,su.L_name,su.NIC,sp.Phone FROM student su INNER JOIN stu_phone sp on su.Stu_id = sp.Stu_id ";
                //"SELECT su.Stu_id,su.F_name,su.L_name,su.NIC,sp.Phone FROM student su INNER JOIN stu_phone sp on su.Stu_id = sp.Stu_id WHERE su.Stu_id= 'BSC-UGC-MIS-15.2-001'";
        Statement st;
        ResultSet rs;
        try {
            st=conn.createStatement();
            rs=st.executeQuery(query);
            ResultPhonec resultPhonec;
            
            while(rs.next())
            {
                resultPhonec=new ResultPhonec(
                        rs.getString("Stu_id"),
                        rs.getString("F_name"),
                        rs.getString("L_name"),
                        rs.getString("NIC"),
                        rs.getString("Phone"));
               ResultPhonecList.add(resultPhonec);
            }
        } catch (SQLException e) {
        }
        return ResultPhonecList;
    }
    
    public void Show_ResultPhone_In_JTable()
    {
         ArrayList<ResultPhonec> List = getResultPhonecList();
         DefaultTableModel model =(DefaultTableModel)jTableResultPhone.getModel();
         Object[] row = new Object[10];
          for (int i = 0; i< List.size();i++) {
            
              row[0]= List.get(i). getStu_id();
              row[1]= List.get(i). getFirst_name();
              row[2]= List.get(i). getLast_name();
              row[3]= List.get(i). getNIC();
              row[4]= List.get(i). getPhone();
              
              model.addRow(row);
            
        }
    }
    
    //execute the sql querys 
    public void executeQuery(String query,String message){
        Connection conn = MysqlConnect.ConnectDB();
        Statement st;
        
        try{
        st=conn.createStatement();
        if((st.executeUpdate(query))== 1)
        {
            
            //refresh the jtable
            DefaultTableModel model = ( DefaultTableModel)jTableResultPhone.getModel();
            model.setRowCount(0);
            Show_ResultPhone_In_JTable();
            
            JOptionPane.showMessageDialog(null,"data"+ message+"Successfully");
        }else
            JOptionPane.showMessageDialog(null,"data not"+ message);
        
        
    }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
    }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultPhone = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableResultPhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "NIC", "Phone"
            }
        ));
        jTableResultPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultPhoneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableResultPhone);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setText("Student Contacts ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableResultPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultPhoneMouseClicked
      
    
    }//GEN-LAST:event_jTableResultPhoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultPhone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultPhone;
    // End of variables declaration//GEN-END:variables
}
