import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yomal Randunu
 */
public final class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        Show_Student_In_JTable();
    }
    
    
        
    
    public ArrayList<Student> getStudentList()
    {
        Connection conn=null;
        ArrayList<Student> StudentList = new ArrayList<Student>(); 
        conn=MysqlConnect.ConnectDB();
        String query="SELECT * FROM  student"; 
        Statement st;
        ResultSet rs;
        try {
            st=conn.createStatement();
            rs=st.executeQuery(query);
            Student student;
            
            while(rs.next())
            {
                student=new Student(rs.getString("Stu_id"),
                        rs.getString("F_name"),
                        rs.getString("M_name"),
                        rs.getString("L_name"),
                        rs.getString("email"),
                        rs.getString("NIC"),
                        rs.getString("Address"),
                        rs.getString("Batch_id"));
                StudentList.add(student);
            }
        } catch (SQLException e) {
        }
        return StudentList;
    }
    
    public void Show_Student_In_JTable()
    {
         ArrayList<Student> List = getStudentList();
         DefaultTableModel model =(DefaultTableModel)jTablestudent.getModel();
         Object[] row = new Object[8];
          for (int i = 0; i< List.size();i++) {
            
              row[0]= List.get(i). getStu_id();
              row[1]= List.get(i). getFirst_name();
              row[2]= List.get(i). getMiddle_name();
              row[3]= List.get(i). getLast_name();
              row[4]= List.get(i). getemail();
              row[5]= List.get(i). getNIC();
              row[6]= List.get(i). getAddress();
              row[7]= List.get(i). getBatch_id();
              
              model.addRow(row);
            
        }
    }
    
    //execute the sql querys 
    public void executeQuery(String query,String message){
        Connection conn = MysqlConnect.ConnectDB();
        Statement st;
        
        try{
        st=conn.createStatement();
        if((st.executeUpdate(query))== 1)
        {
            
            //refresh the jtable
            DefaultTableModel model = ( DefaultTableModel)jTablestudent.getModel();
            model.setRowCount(0);
            Show_Student_In_JTable();
            
            JOptionPane.showMessageDialog(null,"data"+ message+"Successfully");
        }else
            JOptionPane.showMessageDialog(null,"data not"+ message);
        
        
    }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
    }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldmiddle = new javax.swing.JTextField();
        jTextFieldlast = new javax.swing.JTextField();
        jTextFieldfirst = new javax.swing.JTextField();
        jTextFieldaddress = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldnic = new javax.swing.JTextField();
        jToggleButtonsave1 = new javax.swing.JToggleButton();
        jTextFieldid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldbatchid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jToggleButtonupdate1 = new javax.swing.JToggleButton();
        jToggleButtondelete1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablestudent = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Student Name");

        jLabel3.setText("Student Id");

        jLabel4.setText("Middle Name");

        jLabel5.setText("Last Name");

        jLabel6.setText("Address");

        jLabel7.setText("E-Mail ");

        jTextFieldmiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmiddleActionPerformed(evt);
            }
        });

        jLabel8.setText("NIC");

        jToggleButtonsave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/19-32.png"))); // NOI18N
        jToggleButtonsave1.setText("Insert");
        jToggleButtonsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonsave1ActionPerformed(evt);
            }
        });

        jLabel10.setText("First Name");

        jLabel11.setText("Batch Id");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Student Details");

        jToggleButtonupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/43-32.png"))); // NOI18N
        jToggleButtonupdate1.setText("Update");
        jToggleButtonupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonupdate1ActionPerformed(evt);
            }
        });

        jToggleButtondelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/50-32.png"))); // NOI18N
        jToggleButtondelete1.setText("Delete");
        jToggleButtondelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtondelete1ActionPerformed(evt);
            }
        });

        jTablestudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Middle Name", "Last Name", "Email", "NIC", "Address", "Batch ID"
            }
        ));
        jTablestudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablestudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablestudent);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("University Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(jTextFieldnic)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldmiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldlast, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldbatchid))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToggleButtondelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldmiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldbatchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonsave1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtondelete1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonupdate1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonsave1ActionPerformed
/*        String Student_id = jTextFieldid.getText();
        String first_name = jTextFieldfirst.getText();
        String middle_name = jTextFieldmiddle.getText();
        String last_name = jTextFieldlast.getText();
        String address = jTextFieldaddress.getText();
        String email = jTextFieldemail.getText();
        String nic = jTextFieldnic.getText();
        String Batch_id = jTextFieldbatchid.getText();
        Connection conn =null;
        PreparedStatement pst=null;
        try{
            conn=MysqlConnect.ConnectDB();
            pst=conn.prepareStatement("INSERT INTO student VALUES (?,?,?, ?, ?, ?, ?,?)");
            pst.setString(1, Student_id);
            pst.setString(2, first_name);
            pst.setString(3, middle_name);
            pst.setString(4, last_name);
            pst.setString(5, email);
            pst.setString(6, nic);
            pst.setString(7, address);
            pst.setString(8, Batch_id);
             int i = pst.executeUpdate();
             if(i>0){
                 JOptionPane.showMessageDialog(null, "Data Save");
                 
             }else
                  JOptionPane.showMessageDialog(null, "Data not save");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
            
        }
        
       */

 
     String query="INSERT INTO `university`.`Student` (`Stu_id`, `F_name`, `M_name`, `L_name`,`email`,`NIC`,`Address`,`Batch_id`) VALUES ('"+jTextFieldid.getText()+"','"+jTextFieldfirst.getText()+"','"+jTextFieldmiddle.getText()+"','"+jTextFieldlast.getText()+"','"+jTextFieldemail.getText()+"','"+jTextFieldnic.getText()+"','"+jTextFieldaddress.getText()+"','"+jTextFieldbatchid.getText()+"')";
       executeQuery(query,"inserted");   
         
        
     
          
    }//GEN-LAST:event_jToggleButtonsave1ActionPerformed

    private void jTextFieldmiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmiddleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmiddleActionPerformed

    private void jToggleButtonupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonupdate1ActionPerformed
   String query = " UPDATE `university`.`student` SET `Stu_id`='"+jTextFieldid.getText()+"', `F_name`='"+jTextFieldfirst.getText()+"', `M_name`='"+jTextFieldmiddle.getText()+"', `L_name`='"+jTextFieldlast.getText()+"', `email`='"+jTextFieldemail.getText()+"', `NIC`='"+jTextFieldnic.getText()+"', `Address`='"+jTextFieldaddress.getText()+"',`Batch_id`='"+jTextFieldbatchid.getText()+"' WHERE `Stu_id`='"+jTextFieldid.getText()+"'";
      // UPDATE `university`.`student` SET `Stu_id`='"+jTextFieldid.getText()+"', `F_name`='"+jTextFieldfirst.getText()+"', `M_name`='"+jTextFieldmiddle.getText()+"', `L_name`='"+jTextFieldlast.getText()+"', `email`='"+jTextFieldemail.getText()+"', `NIC`='"+jTextFieldnic.getText()+"', `Address`='"+jTextFieldaddress.getText()+"',`Batch_id`='"+jTextFieldbatchid.getText()+"' WHERE `Stu_id`='"+jTextFieldid.getText()"';
        executeQuery(query, "Inserted");
      
    
    }//GEN-LAST:event_jToggleButtonupdate1ActionPerformed

    private void jTablestudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablestudentMouseClicked
        int i =jTablestudent.getSelectedRow();
        TableModel model = jTablestudent.getModel();
        jTextFieldid.setText(model.getValueAt(i,0).toString());
        jTextFieldfirst.setText(model.getValueAt(i,1).toString());
        jTextFieldmiddle.setText(model.getValueAt(i,2).toString());
        jTextFieldlast.setText(model.getValueAt(i,3).toString());
        jTextFieldemail.setText(model.getValueAt(i,4).toString());
        jTextFieldnic.setText(model.getValueAt(i,5).toString());
        jTextFieldaddress.setText(model.getValueAt(i,6).toString());
        jTextFieldbatchid.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_jTablestudentMouseClicked

    private void jToggleButtondelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtondelete1ActionPerformed
      String query = "DELETE FROM student WHERE `Stu_id`='"+jTextFieldid.getText()+"'"; 
      executeQuery(query, "Deleted");
    }//GEN-LAST:event_jToggleButtondelete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablestudent;
    private javax.swing.JTextField jTextFieldaddress;
    private javax.swing.JTextField jTextFieldbatchid;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldfirst;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldlast;
    private javax.swing.JTextField jTextFieldmiddle;
    private javax.swing.JTextField jTextFieldnic;
    private javax.swing.JToggleButton jToggleButtondelete1;
    private javax.swing.JToggleButton jToggleButtonsave1;
    private javax.swing.JToggleButton jToggleButtonupdate1;
    // End of variables declaration//GEN-END:variables

   
}
